# SearXNG configuration for Personal AI.
use_default_settings: true

search:
  formats:
    - html
    - json
  safe_search: 1

server:
  method: "GET"
  secret_key: "ultrasecretkey"
  limiter: false
  public_instance: false
  image_proxy: false

outgoing:
  request_timeout: 6.0
  max_request_timeout: 10.0

engines:
  - name: wikipedia
    disabled: true

  - name: duckduckgo
    disabled: true

  - name: google cse
    disabled: true

  - name: google scholar
    disabled: true

  - name: startpage
    disabled: true

  - name: brave
    disabled: true

  - name: reuters
    disabled: true

  - name: stackoverflow
    disabled: true
